[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.18.19"
solana-cli-config = "1.18.19"
solana-clap-utils = "1.18.19"
solana-sdk = "1.18.19"
borsh = { version = "1.5.1", features = ["derive"] }
