[package]
name = "sol002-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = "0.30.1"
# anchor-client = { version = "0.30.1 ", features = ["async"] }
anyhow = "1.0.86"
shellexpand = "3.1.0"
solana-sdk = "2.0.3"
