[package]
name = "counter_aclient"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = { version = "0.30.1 " }
anyhow = "1.0.86"
counter = { path = "../programs/counter" }
shellexpand = "3.1.0"
solana-sdk = "2.0.3"
