[package]
name = "initialize"
version = "0.1.0"
edition = "2021"

[dependencies]
counter = { path = "../../programs/counter" }
anchor-client = "0.30.1"
anyhow = "1.0.86"
shellexpand = "3.1.0"
solana-sdk = "2.0.3"
anchor-lang = "0.30.1"
